image:
  file: .gitpod.Dockerfile

tasks:
- init: |
    poetry install
- name: tailscaled
  command: |
    sudo tailscaled
- name: tailscale
  command: |
    sudo -E tailscale up --auth-key $TS_KEY_WORKSPACE --hostname="gitpod-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)" --ssh
